/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Nayel
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGestionProduc = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trabajo-en-equipo.png"))); // NOI18N
        btnGestionUser.setActionCommand("");
        btnGestionUser.setBorder(null);
        btnGestionUser.setBorderPainted(false);
        btnGestionUser.setContentAreaFilled(false);
        btnGestionUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 141, 80));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Inicio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        btnGestionProduc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/datos.png"))); // NOI18N
        btnGestionProduc.setActionCommand("");
        btnGestionProduc.setBorder(null);
        btnGestionProduc.setBorderPainted(false);
        btnGestionProduc.setContentAreaFilled(false);
        btnGestionProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProducActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, 80));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar32.png"))); // NOI18N
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar32.png"))); // NOI18N
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar38.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/thumb2-blue-pink-paper-background-pink-paper-texture-creative-background-paper-backgrounds.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUserActionPerformed
        GestUsuarios form=new GestUsuarios();
         form.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnGestionUserActionPerformed

    private void btnGestionProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProducActionPerformed
        GestProductos form=new GestProductos();
         form.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnGestionProducActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Login form=new Login();
         form.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGestionProduc;
    private javax.swing.JButton btnGestionUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
